name: ${project.artifactId}
version: ${project.version}
main: me.dreamdevs.github.huntergame.HunterGameMain
api-version: 1.13

commands:
  huntergame:
    description: HunterGame commands to configure server
    aliases: [hg]